[package]
name = "IslandBoot"
version = "0.1.0"
edition = "2021"
description = "Stage 2 code for IslandBoot."
license = "MIT"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build]
target = "x86_64-my_target.json"

[[bin]]
name = "stage2"
path = "main.rs"
